from enum import Enum


class CardType(Enum):
    PYTHIA8 = "pythia8"
    MADSPIN = "madspin"
    RUNCARD = "runcard"


class CardTemplateManager:
    def __init__(self):
        self.templates = {
            CardType.PYTHIA8: self._pythia8_template(),
            CardType.MADSPIN: self._madspin_template(),
            CardType.RUNCARD: self._runcard_template()
        }

    def get(self, card_type: CardType) -> str:
        if card_type not in self.templates:
            raise ValueError(f"Template not found for card type: {card_type}")
        return self.templates[card_type]

    def _pythia8_template(self) -> str:
        return """!
! Pythia8 cmd card automatically generated by MadGraph5_aMC@NLO
! For more information on the use of the MG5aMC / Pythia8 interface, visit
!    https://cp3.irmp.ucl.ac.be/projects/madgraph/wiki/LOPY8Merging
!
! ==================
! General parameters 
! ==================
!
Main:numberOfEvents      = -1
HEPMCoutput:file         = hepmc.gz
JetMatching:qCut         = -1.0
JetMatching:doShowerKt   = off
JetMatching:nJetMax      = -1
Merging:TMS              = -1.0
Merging:Process          = <set_by_user>
Merging:nJetMax  		 = -1
SysCalc:fullCutVariation = off
!
! -------------------------------------------------------------------
! Specify the HEPMC output of the Pythia8 shower...

PartonLevel:ISR = on
PartonLevel:FSR = on

9900012:mayDecay = off
9900014:mayDecay = off
9900016:mayDecay = off

LesHouches:setLifetime = 0 
"""

    def _madspin_template(self) -> str:
        return """#************************************************************
#*                        MadSpin                           *
#*                                                          *
#*    P. Artoisenet, R. Frederix, R. Rietkerk, O. Mattelaer * 
#*                                                          *
#*    Part of the MadGraph5_aMC@NLO Framework...
 set spinmode none
 set max_weight_ps_point 400

decay t > w+ b, w+ > all all
decay t~ > w- b~, w- > all all
decay w+ > all all
decay w- > all all
decay z > all all
launch
"""
    def _runcard_template(self) -> str:
        return """#*********************************************************************
#                       MadGraph5_aMC@NLO                            
#                                                                    
#                     run_card.dat MadEvent                          
#                                                                    
#  This file is used to set the parameters of the run.               
#                                                                    
#   Lines starting with a '# ' are info or comments                  
#   mind the format:   value    = variable     ! comment             
#*********************************************************************

  tag_1  = run_tag                     ! name of the run
  2000   = nevents                    ! Number of unweighted events requested
  0      = iseed                     ! random seed (0 = auto)
  0.001 = req_acc ! required accuracy (-1 = auto determined from nevents)
  -1  = nevt_job

  1      = lpp1                      ! beam 1 type (1=proton)
  1      = lpp2                      ! beam 2 type
  7000.0 = ebeam1                    ! beam 1 energy in GeV
  7000.0 = ebeam2                    ! beam 2 energy in GeV

  nn23lo1 = pdlabel                  ! PDF set
  230000  = lhaid                    ! LHAPDF ID

  False   = fixed_ren_scale
  False   = fixed_fac_scale
  91.188  = scale
  91.188  = dsqrt_q2fact1
  91.188  = dsqrt_q2fact2
  -1      = dynamical_scale_choice
  1.0     = scalefact

  False   = gridpack
  0.0	= time_of_flight
  average = event_norm

  0       = nhel
  2       = sde_strategy

           = custom_fcts

  0.0     = dsqrt_shat

  15.0    = bwcutoff
  True    = cut_decays

  {}      = pt_min_pdg
  {}      = pt_max_pdg

  -1.0    = etaj
  -1.0    = etal
  -1.0    = etajmin
  -1.0    = etalmin
  {}      = eta_min_pdg
  {}      = eta_max_pdg

  -1.0    = drjj
  -1.0    = drll
  -1.0    = drjl
  -1.0    = drjjmax
  -1.0    = drllmax
  -1.0    = drjlmax

  -1.0    = mmjj
  -1.0    = mmll
  -1.0    = mmjjmax
  -1.0    = mmllmax
  {}      = mxx_min_pdg
  {'default': False} = mxx_only_part_antipart

  -1.0    = mmnl
  -1.0    = mmnlmax
  -1.0    = ptllmin
  -1.0    = ptllmax

  -1.0    = xptj
  -1.0    = xptl

  -1.0    = ptj1min
  -1.0    = ptj2min
  -1.0    = ptj1max
  -1.0    = ptj2max
  0       = cutuse

  -1.0    = ptl1min
  -1.0    = ptl2min
  -1.0    = ptl3min
  -1.0    = ptl1max
  -1.0    = ptl2max
  -1.0    = ptl3max

  -1.0    = htjmin
  -1.0    = htjmax
  -1.0    = ihtmin
  -1.0    = ihtmax

  -1.0    = xetamin
  -1.0    = deltaeta

  4       = maxjetflavor

  False    = use_syst
  systematics = none
  !systematics = systematics_program
  !['--mur=0.5,1,2', '--muf=0.5,1,2', '--pdf=errorset'] = systematics_arguments
"""

if __name__ == "__main__":
    manager = CardTemplateManager()
    print(manager.get(CardType.RUNCARD)) 
